nameOverride: ""
fullnameOverride: ""

agents:
  serviceAccount:
    create: true
    annotation: {}
    name: ""

server:
  image:
    repository: jenkins/jenkins
    pullPolicy: Always
    tag: ""

  persistence:
    storageClassName: ""
    size: 10Gi

  imagePullSecrets: []

  serviceAccount:
    create: true
    annotations: {}
    name: ""

  podAnnotations: {}

  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 2
      memory: 512Mi

  podSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true

  service:
    type: ClusterIP
    port: 8080

  ingress:
    enabled: false
    className: ""
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

  nodeSelector: {}
  tolerations: []
  affinity: {}
