---

nameOverride: ""
fullnameOverride: ""
extraEnv: {}

server:
  image:
    repository: zabbix/zabbix-server-pgsql
    pullPolicy: Always
    tag: ""

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  extraEnv: {}

  extraVolumes: []

  extraVolumeMounts: []

  serviceAccount:
    create: true
    annotations: {}
    name: ""

  podAnnotations: {}

  podSecurityContext:
    runAsUser: 10000
    runAsGroup: 10000
    fsGroup: 10000

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true

  service:
    type: ClusterIP
    port: 10051

  resources: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}

web:
  replicaCount: 1

  image:
    repository: zabbix/zabbix-web-nginx-pgsql
    pullPolicy: Always
    tag: ""

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  extraEnv: {}

  serviceAccount:
    create: true
    annotations: {}
    name: ""

  podAnnotations: {}

  podSecurityContext:
    runAsUser: 10000
    runAsGroup: 10000
    fsGroup: 10000

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true

  service:
    type: ClusterIP
    port: 8080

  ingress:
    enabled: false
    className: ""
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

  resources: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}
