#!/bin/sh

s6-setuidgid rutorrent \
  mkdir --parents \
    /run/nginx \
    /run/nginx/body \
    /run/nginx/fastcgi \
    /run/nginx/proxy \
    /run/nginx/scgi \
    /run/nginx/uwsgi

exec s6-setuidgid rutorrent \
  /usr/sbin/nginx -c /config/nginx/nginx.conf
