apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mongo.fullname" . }}-data
  labels:
    {{- include "mongo.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.mongo.persistence.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.mongo.persistence.size }}
