{{- if .Values.mongo.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mongo.serviceAccountName" . }}
  labels:
    {{- include "mongo.labels" . | nindent 4 }}
  {{- with .Values.mongo.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
