apiVersion: v1
kind: Service
metadata:
  name: {{ include "unifi.mongo.fullname" . }}
  labels:
    {{- include "unifi.mongo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mongo.service.type }}
  ports:
    - port: {{ .Values.mongo.service.port }}
      targetPort: mongo
      protocol: TCP
      name: mongo
  selector:
    {{- include "unifi.mongo.selectorLabels" . | nindent 4 }}
