apiVersion: v1
kind: Service
metadata:
  name: {{ include "unifi.fullname" . }}
  labels:
    {{- include "unifi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.stun }}
      targetPort: stun
      protocol: UDP
      name: stun
    - port: {{ .Values.service.ports.controller }}
      targetPort: controller
      protocol: TCP
      name: controller
    - port: {{ .Values.service.ports.https }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "unifi.selectorLabels" . | nindent 4 }}
