apiVersion: v1
kind: Service
metadata:
  name: {{ include "unifi.unifi.fullname" . }}
  labels:
    {{- include "unifi.unifi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.unifi.service.type }}
  ports:
    - port: {{ .Values.unifi.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "unifi.unifi.selectorLabels" . | nindent 4 }}
