apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "unifi.fullname" . }}
  labels:
    {{- include "unifi.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.unifi.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "unifi.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.unifi.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "unifi.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.unifi.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "unifi.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.unifi.podSecurityContext | nindent 8 }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "unifi.fullname" . }}-data
        - name: tmp
          emptyDir: {}
        - name: run
          emptyDir: {}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.unifi.securityContext | nindent 12 }}
          image: "{{ .Values.unifi.image.repository }}:{{ .Values.unifi.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.unifi.image.pullPolicy }}
          {{- with .Values.unifi.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: stun
              protocol: UDP
              containerPort: 3478
            - name: controller
              protocol: TCP
              containerPort: 8080
            - name: https
              protocol: TCP
              containerPort: 8443
          startupProbe:
            httpGet:
              path: /status
              port: https
              scheme: HTTPS
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /status
              port: https
              scheme: HTTPS
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /status
              port: https
              scheme: HTTPS
            periodSeconds: 30
          volumeMounts:
            - name: data
              mountPath: /unifi
            - name: run
              mountPath: /run
            - name: tmp
              mountPath: /tmp
          resources:
            {{- toYaml .Values.unifi.resources | nindent 12 }}
      {{- with .Values.unifi.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.unifi.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.unifi.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
