apiVersion: v1
kind: Service
metadata:
  name: {{ include "unifi.fullname" . }}-controller
  labels:
    {{- include "unifi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.unifi.service.controller.type }}
  ports:
    - port: {{ (index .Values.unifi.service.controller.ports 0).port }}
      targetPort: {{ (index .Values.unifi.service.controller.ports 0).name }}
      protocol: UDP
      name: {{ (index .Values.unifi.service.controller.ports 0).name }}
    - port: {{ (index .Values.unifi.service.controller.ports 1).port }}
      targetPort: {{ (index .Values.unifi.service.controller.ports 1).name }}
      protocol: TCP
      name: {{ (index .Values.unifi.service.controller.ports 1).name }}
  selector:
    {{- include "unifi.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "unifi.fullname" . }}-https
  labels:
    {{- include "unifi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.unifi.service.https.type }}
  ports:
    - port: {{ .Values.unifi.service.https.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "unifi.selectorLabels" . | nindent 4 }}
