apiVersion: v1
kind: Service
metadata:
  name: {{ include "unifi.fullname" . }}-controller
  labels:
    {{- include "unifi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.unifi.service.controller.type }}
  ports:
    - port: {{ .Values.unifi.service.controller.ports.stun }}
      targetPort: {{ .Values.unifi.service.controller.ports.stun }}
      protocol: UDP
      name: stun
      {{- if .Values.unifi.service.controller.nodePorts.stun }}
      nodePort: {{ .Values.unifi.service.controller.nodePorts.stun }}
      {{- end }}
    - port: {{ .Values.unifi.service.controller.ports.controller }}
      targetPort: {{ .Values.unifi.service.controller.ports.controller }}
      {{- if .Values.unifi.service.controller.nodePorts.controller }}
      nodePort: {{ .Values.unifi.service.controller.nodePorts.controller }}
      {{- end }}
      protocol: TCP
      name: controller
  selector:
    {{- include "unifi.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "unifi.fullname" . }}-https
  labels:
    {{- include "unifi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.unifi.service.https.type }}
  ports:
    - port: {{ .Values.unifi.service.https.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "unifi.selectorLabels" . | nindent 4 }}
