apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "unifi.fullname" . }}-data
  labels:
    {{- include "unifi.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.unifi.persistence.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.unifi.persistence.size }}
