{{- if .Values.unifi.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "unifi.unifi.serviceAccountName" . }}
  labels:
    {{- include "unifi.unifi.labels" . | nindent 4 }}
  {{- with .Values.unifi.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
