apiVersion: v1
kind: Service
metadata:
  name: {{ include "acmedns.fullname" . }}-api
  labels:
    {{- include "acmedns.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.api.type }}
  ports:
    - port: {{ .Values.service.api.port }}
      targetPort: api
      protocol: TCP
      name: api
      {{- with .Values.service.api.nodePort }}
      nodePort: {{ . }}
      {{- end }}
  selector:
    {{- include "acmedns.selectorLabels" . | nindent 4 }}
