apiVersion: v1
kind: Service
metadata:
  name: {{ include "acmedns.fullname" . }}-dns
  labels:
    {{- include "acmedns.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.dns.type }}
  ports:
    - port: {{ .Values.service.dns.port }}
      targetPort: dns
      protocol: UDP
      name: dns
      {{- with .Values.service.dns.nodePort }}
      nodePort: {{ . }}
      {{- end }}
  selector:
    {{- include "acmedns.selectorLabels" . | nindent 4 }}
