apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "postgres.fullname" . }}-data
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.postgres.persistence.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size }}
