apiVersion: v1
kind: Service
metadata:
  name: {{ include "server.fullname" . }}
  labels:
    {{- include "server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: zabbix
      protocol: TCP
      name: zabbix
      {{- if .Values.server.service.nodePort }}
      nodePort: {{ .Values.server.service.nodePort }}
      {{- end }}
  selector:
    {{- include "server.selectorLabels" . | nindent 4 }}
