apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "server.fullname" . }}
  labels:
    {{- include "server.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "server.fullname" . }}
  replicas: {{ .Values.server.replicaCount }}
  selector:
    matchLabels:
      {{- include "server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.server.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "server.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: zabbix
          emptyDir: {}
        - name: tmp
          emptyDir: {}
      {{- with .Values.server.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "server.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.server.podSecurityContext | nindent 8 }}
      initContainers:
        - name: init
          securityContext:
            {{- toYaml .Values.server.securityContext | nindent 12 }}
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          command: [ "/bin/sh" ]
          args: ["-c", "cp --recursive /etc/zabbix/* /tmp/zabbix"]
          volumeMounts:
            - name: zabbix
              mountPath: /tmp/zabbix
          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
      containers:
        - name: zabbix-server
          securityContext:
            {{- toYaml .Values.server.securityContext | nindent 12 }}
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          ports:
            - name: zabbix
              containerPort: {{ .Values.server.service.port }}
              protocol: TCP
          volumeMounts:
            - name: zabbix
              mountPath: /etc/zabbix
            - name: tmp
              mountPath: /tmp
          readinessProbe:
            tcpSocket:
              port: zabbix
          livenessProbe:
            tcpSocket:
              port: zabbix
          {{- with .Values.server.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
      {{- with .Values.server.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
