apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "server.fullname" . }}
  labels:
    {{- include "server.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.server.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "server.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: config
          emptyDir: {}
        - name: tmp
          emptyDir: {}
      {{- with .Values.server.extraVolumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "server.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.server.podSecurityContext | nindent 8 }}
      initContainers:
        - name: init
          securityContext:
            {{- toYaml .Values.server.securityContext | nindent 12 }}
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          command:
            - "/bin/cp"
          args:
            - "-f"
            - "-r"
            - "/etc/zabbix/."
            - "/config"
          volumeMounts:
            - name: config
              mountPath: /config
          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
      containers:
        - name: zabbix-server
          securityContext:
            {{- toYaml .Values.server.securityContext | nindent 12 }}
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          ports:
            - name: zabbix-server
              containerPort: {{ .Values.server.service.port }}
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/zabbix
            - name: tmp
              mountPath: /tmp
          {{- with .Values.server.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          startupProbe:
            tcpSocket:
              port: zabbix-server
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: zabbix-server
            periodSeconds: 30
          livenessProbe:
            tcpSocket:
              port: zabbix-server
            periodSeconds: 30
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ include "zabbix.fullname" . }}-database-credentials"
                  key: POSTGRES_PASSWORD
            {{- range $k, $v := .Values.extraEnv }}
            - name: {{ $k }}
              value: "{{ $v }}"
            {{- end }}
            {{- range $k, $v := .Values.server.extraEnv }}
            - name: {{ $k }}
              value: "{{ $v }}"
            {{- end }}
          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
      {{- with .Values.server.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
