{{- if .Values.web.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "web.serviceAccountName" . }}
  labels:
    {{- include "web.labels" . | nindent 4 }}
  {{- with .Values.web.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
