apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "jenkins.fullname" . }}-agents
  namespace: {{ include "jenkins.agents.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "jenkins.fullname" . }}-agents
subjects:
- kind: ServiceAccount
  name: {{ include "jenkins.agents.serviceAccountName" . }}
  namespace: {{ include "jenkins.agents.namespace" . }}
