apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "jenkins.fullname" . }}-agents
  namespace: {{ include "jenkins.agents.namespace" . }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
