{{- if .Values.agents.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "jenkins.agents.serviceAccountName" . }}
  labels:
    {{- include "jenkins.labels" . | nindent 4 }}
  {{- with .Values.agents.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
