apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "jenkins.fullname" . }}
  labels:
    {{- include "jenkins.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "jenkins.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "jenkins.selectorLabels" . | nindent 6 }}
  volumeClaimTemplates:
    - metadata:
        name: {{ include "jenkins.fullname" . }}
      spec:
        accessModes:
          - "ReadWriteOnce"
        storageClassName: {{ .Values.persistence.storageClassName }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "jenkins.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "jenkins.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: tmp
          emptyDir: {}
      initContainers:
        - name: init
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ /usr/bin/install ]
          args: [ "-d", "-m", "0700", "-o", "10000", "-g", "10000", "/var/jenkins_home" ]
          securityContext:
            runAsNonRoot: false
            runAsUser: 0
            capabilities:
              add:
                - DAC_OVERRIDE
                - FOWNER
                - CHOWN
              drop:
                - ALL
          volumeMounts:
            - name: {{ include "jenkins.fullname" . }}
              mountPath: /var/jenkins_home
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: {{ include "jenkins.fullname" . }}
              mountPath: /var/jenkins_home
            - name: tmp
              mountPath: /tmp
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          startupProbe:
            httpGet:
              path: /robots.txt
              port: http
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /robots.txt
              port: http
          readinessProbe:
            httpGet:
              path: /robots.txt
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
